name: Tests

on:
  pull_request:
    branches:
      - 'master'
      - 'main'
      - 'dev'
      - '*'
  push:
    branches:
      - 'master'
      - 'main'
      - 'dev'
jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: cffdev
          POSTGRES_PASSWORD: hunter2
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v2

    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true

    - name: Install PostgreSQL client
      run: |
        sudo apt-get -yqq install libpq-dev

    - name: Build App
      env:
        PGHOST: localhost
        PGUSER: cffdev
        PGPASSWORD: hunter2
        RAILS_ENV: test
      run: |
        bin/rails db:create
        bin/rails db:migrate

    - name: Lint FactoryBot Fixtures
      env:
        PGHOST: localhost
        PGUSER: cffdev
        PGPASSWORD: hunter2
        RAILS_ENV: test
      run: |
        bundle exec rake factory_bot:lint

    - name: Run Specs
      env:
        PGHOST: localhost
        PGUSER: cffdev
        PGPASSWORD: hunter2
        RAILS_ENV: test
      run: |
        bundle exec rspec -f documentation

    - name: Run Tests
      env:
        PGHOST: localhost
        PGUSER: cffdev
        PGPASSWORD: hunter2
        RAILS_ENV: test
      run: |
        bundle exec rake test
        # bundle exec rake test:system
        # or Rspec
        # bundle exec rspec
